### ISSUE TITLE
Can I edit this lecture in yanshuo.io?

### ISSUE THREAD

**Issue by chinesedfan** [Huxpro/pwa-qcon2016#1]
I found no .shuo file in this project.

**Comment by Huxpro** [comment]
Ah... forgive my curiosity, what are you gonna play with it? This talk/slides was originally intended to be a less-technical thus less-universal one, kinda personal and opinionated storytelling. So I thought pushing `.shuo` up make little sense. Nonetheless contributions or redistributions are welcome.

**Comment by chinesedfan** [comment]
Well, I got a "political task" to re-share your lecture to my colleagues. As you said, the slides was less-technical, so I need to prune some background introduction and focus on PWA technique itself.

At least, can you send the .shuo file to my github email? Thank you all the same if not conveniently.

**Comment by Huxpro** [comment]
Hmm...It's weird that you have such a task...
Anyway, It's comfortable to me to "open source" it under BSD. 
Checking out <https://github.com/Huxpro/pwa-qcon2016/tree/master/shuo>, enjoy!

**Comment by chinesedfan** [comment]
Great!

It is easy to understand. The company pays, the boss attends, and I share. :)
